# 输入item信息，跑生成embedding

## 一. 图片主体检测+特征提取
Bottom-up Attention with detectron2 环境安装 参见readme.md,需要torch==1.4版本环境

In [22]:
%pwd

'/home/admin/workspace/project/Capture_open/py-bottom-up-attention'

In [43]:
cd /home/admin/workspace/project/Capture_open

/home/admin/workspace/project/Capture_open


In [44]:
%run bp_feature/extract_feature_unit.py --input_file '../item_valid_info.jsonl' --local_image_path '../item_valid_images/item_valid_images' \
  --output_file './testv1/item_valid_image_feature.csv'  --save_model_path './bp_feature/faster_rcnn_from_caffe_attr.pkl'

RuntimeError: name.name() == def.name().name() INTERNAL ASSERT FAILED at /pytorch/torch/csrc/jit/script/init.cpp:844, please report a bug to PyTorch.  (operator() at /pytorch/torch/csrc/jit/script/init.cpp:844)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f3b53fd6193 in /home/pai/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x77a606 (0x7f3b9f144606 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x2961c4 (0x7f3b9ec601c4 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: _PyCFunction_FastCallDict + 0x154 (0x559fa9722a14 in /home/pai/bin/python)
frame #4: <unknown function> + 0x19aa5c (0x559fa97aaa5c in /home/pai/bin/python)
frame #5: _PyEval_EvalFrameDefault + 0x30a (0x559fa97cd25a in /home/pai/bin/python)
frame #6: <unknown function> + 0x193fd4 (0x559fa97a3fd4 in /home/pai/bin/python)
frame #7: <unknown function> + 0x194e51 (0x559fa97a4e51 in /home/pai/bin/python)
frame #8: <unknown function> + 0x19ab35 (0x559fa97aab35 in /home/pai/bin/python)
frame #9: _PyEval_EvalFrameDefault + 0x10c9 (0x559fa97ce019 in /home/pai/bin/python)
frame #10: PyEval_EvalCodeEx + 0x329 (0x559fa97a5969 in /home/pai/bin/python)
frame #11: <unknown function> + 0x196784 (0x559fa97a6784 in /home/pai/bin/python)
frame #12: PyObject_Call + 0x3e (0x559fa972281e in /home/pai/bin/python)
frame #13: <unknown function> + 0x7cb2f1 (0x7f3b9f1952f1 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0x7bda46 (0x7f3b9f187a46 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #15: <unknown function> + 0x7bedab (0x7f3b9f188dab in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #16: <unknown function> + 0x4288c57 (0x7f3b586b1c57 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #17: <unknown function> + 0x42984fc (0x7f3b586c14fc in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #18: <unknown function> + 0x4288d70 (0x7f3b586b1d70 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #19: <unknown function> + 0x4294176 (0x7f3b586bd176 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #20: <unknown function> + 0x4294eaf (0x7f3b586bdeaf in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #21: <unknown function> + 0x429b241 (0x7f3b586c4241 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #22: <unknown function> + 0x429df54 (0x7f3b586c6f54 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #23: <unknown function> + 0x429f135 (0x7f3b586c8135 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #24: <unknown function> + 0x4269ad4 (0x7f3b58692ad4 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #25: torch::jit::Function::ensure_defined() + 0xca (0x7f3b587692aa in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #26: torch::jit::script::CompilationUnit::define(c10::optional<c10::QualifiedName> const&, std::vector<torch::jit::script::Def, std::allocator<torch::jit::script::Def> > const&, std::vector<std::shared_ptr<torch::jit::script::Resolver>, std::allocator<std::shared_ptr<torch::jit::script::Resolver> > > const&, torch::jit::script::Self const*, bool) + 0x5c8 (0x7f3b58691698 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #27: <unknown function> + 0x774557 (0x7f3b9f13e557 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #28: <unknown function> + 0x77a7cc (0x7f3b9f1447cc in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #29: <unknown function> + 0x2961c4 (0x7f3b9ec601c4 in /home/pai/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #30: _PyCFunction_FastCallDict + 0x154 (0x559fa9722a14 in /home/pai/bin/python)
frame #31: <unknown function> + 0x19aa5c (0x559fa97aaa5c in /home/pai/bin/python)
frame #32: _PyEval_EvalFrameDefault + 0x30a (0x559fa97cd25a in /home/pai/bin/python)
frame #33: <unknown function> + 0x193fd4 (0x559fa97a3fd4 in /home/pai/bin/python)
frame #34: <unknown function> + 0x194e51 (0x559fa97a4e51 in /home/pai/bin/python)
frame #35: <unknown function> + 0x19ab35 (0x559fa97aab35 in /home/pai/bin/python)
frame #36: _PyEval_EvalFrameDefault + 0x30a (0x559fa97cd25a in /home/pai/bin/python)
frame #37: PyEval_EvalCodeEx + 0x329 (0x559fa97a5969 in /home/pai/bin/python)
frame #38: PyEval_EvalCode + 0x1c (0x559fa97a670c in /home/pai/bin/python)
frame #39: <unknown function> + 0x1bab5b (0x559fa97cab5b in /home/pai/bin/python)
frame #40: PyCFunction_Call + 0x131 (0x559fa9725a21 in /home/pai/bin/python)
frame #41: _PyEval_EvalFrameDefault + 0x554a (0x559fa97d249a in /home/pai/bin/python)
frame #42: <unknown function> + 0x193fd4 (0x559fa97a3fd4 in /home/pai/bin/python)
frame #43: <unknown function> + 0x194e51 (0x559fa97a4e51 in /home/pai/bin/python)
frame #44: <unknown function> + 0x19ab35 (0x559fa97aab35 in /home/pai/bin/python)
frame #45: _PyEval_EvalFrameDefault + 0x30a (0x559fa97cd25a in /home/pai/bin/python)
frame #46: <unknown function> + 0x194c1b (0x559fa97a4c1b in /home/pai/bin/python)
frame #47: <unknown function> + 0x19ab35 (0x559fa97aab35 in /home/pai/bin/python)
frame #48: _PyEval_EvalFrameDefault + 0x30a (0x559fa97cd25a in /home/pai/bin/python)
frame #49: <unknown function> + 0x194c1b (0x559fa97a4c1b in /home/pai/bin/python)
frame #50: <unknown function> + 0x19ab35 (0x559fa97aab35 in /home/pai/bin/python)
frame #51: _PyEval_EvalFrameDefault + 0x30a (0x559fa97cd25a in /home/pai/bin/python)
frame #52: <unknown function> + 0x194c1b (0x559fa97a4c1b in /home/pai/bin/python)
frame #53: <unknown function> + 0x19ab35 (0x559fa97aab35 in /home/pai/bin/python)
frame #54: _PyEval_EvalFrameDefault + 0x30a (0x559fa97cd25a in /home/pai/bin/python)
frame #55: _PyFunction_FastCallDict + 0x11b (0x559fa97a528b in /home/pai/bin/python)
frame #56: _PyObject_FastCallDict + 0x26f (0x559fa9722ddf in /home/pai/bin/python)
frame #57: _PyObject_CallMethodIdObjArgs + 0x100 (0x559fa97646a0 in /home/pai/bin/python)
frame #58: PyImport_ImportModuleLevelObject + 0x280 (0x559fa9719970 in /home/pai/bin/python)
frame #59: _PyEval_EvalFrameDefault + 0x2c2f (0x559fa97cfb7f in /home/pai/bin/python)
frame #60: PyEval_EvalCodeEx + 0x329 (0x559fa97a5969 in /home/pai/bin/python)
frame #61: PyEval_EvalCode + 0x1c (0x559fa97a670c in /home/pai/bin/python)
frame #62: <unknown function> + 0x1bab5b (0x559fa97cab5b in /home/pai/bin/python)
frame #63: PyCFunction_Call + 0x131 (0x559fa9725a21 in /home/pai/bin/python)


In [4]:
%run bp_feature/convert_feature_all.py 

  0%|          |0/16876[00:00<?,?it/s]

[0413 10:34:02 @argtools.py:146] WRN "import prctl" failed! Install python-prctl so that processes can be cleaned with guarantee.


100%|#########9|16866/16876[09:41<00:00,29.22it/s]

16876
[0413 10:43:45 @serialize.py:72] Flushing database ...


100%|##########|16876/16876[09:43<00:00,28.94it/s]


In [27]:
## 二. Capture 多模态特征抽取
需要torch>=1.6版本, 可采用两个conda环境分开进行跑

烟斗剃须刀充电往复式电动男士老人头刮胡刀胡子刀鬓角修剪器正品
[[0.0000000e+00 7.8910065e+00 3.7091156e+02 4.4042853e+02]
 [4.2390747e+00 1.0713806e+00 4.4738077e+02 3.8689767e+02]
 [2.3008542e+02 1.8670689e+01 4.0276932e+02 1.3869130e+02]
 [4.4360541e+02 2.2818680e+02 5.2784460e+02 4.7772360e+02]
 [3.0778656e+00 3.8861511e+01 4.4028107e+02 5.5933789e+02]
 [4.1359329e+00 4.7036749e+02 2.5706873e+02 7.4379242e+02]
 [2.5192487e+02 4.3305191e+02 4.3049774e+02 6.8914856e+02]
 [5.6861069e+01 3.1078644e+00 5.0274530e+02 4.9731146e+02]
 [2.7654645e+02 4.5447479e+02 4.1131036e+02 5.9991156e+02]
 [2.3421782e+02 4.1666605e+02 4.5797980e+02 6.5508350e+02]
 [1.2333290e+01 5.2859344e+02 2.4416708e+02 7.6512970e+02]
 [5.1794617e+01 1.4668228e+02 4.3174374e+02 3.7361807e+02]
 [4.2063934e+01 5.1098657e+02 2.1385567e+02 7.9166809e+02]
 [0.0000000e+00 2.8414795e+01 3.5751083e+02 6.2023877e+02]
 [2.2920731e+01 4.4674536e+02 2.1045209e+02 7.8664954e+02]
 [4.8038025e+00 1.6347516e+02 4.0942947e+02 3.9520459e+02]
 [4.4381644e+02 1.1421568

NameError: name 'ss' is not defined

In [8]:
cd capture

/home/admin/workspace/project/Capture_open/capture


In [41]:
!sh run_inference.sh




04/13/2022 16:06:35 - INFO - capture.capture -   Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
Namespace(CLR=False, ITM=False, MLM=False, MRM=False, baseline=False, bert_model='bert-base-chinese', caption_path='../../item_valid_info.jsonl', config_file='./config/capture.json', distributed=False, do_lower_case=True, fp16=False, freeze=-1, from_pretrained='./pytorch_model_8.bin', gradient_accumulation_steps=1, img_weight=1, label_list_file=None, learning_rate=0.0001, lmdb_file='../testv1/item_valid_image_feature.lmdb', local_rank=-1, loss_scale=0, max_seq_length=36, no_cuda=False, num_train_epochs=10.0, num_workers=3, on_memory=False, output_dir='./testv1', predict_feature=True, save_name='', seed=42, start_epoch=0, test_lmdb_file=None, train_batch_size=64, train_file='data/conceptual_caption/training', train_lmdb_file=None, use_chuncks=0, validation_file='data/conceptual_caption/validation', warmup_proportion=0.1, without_coattention=False

In [31]:
import torch
torch.__version__

'1.4.0'

In [ ]:
## 三. F1 测评

In [ ]:
## 四. 结果提交

In [ ]:
import json
import os
import csv
itemid2emb = {}
# 读取embedding文件
with open('./capture/testv1/item_features.tsv') as tsv_in_file:
    reader = csv.DictReader(tsv_in_file, delimiter='\t', fieldnames=['item_id', 'features'])
    for item in reader:
        itemid2emb[str(item['item_id'])] = '[' + item['features'] + ']'
        # print(item['item_id'])
print(len(itemid2emb))
        

f_out = open('./result.jsonl', encoding='utf-8', mode='w')
with open('../item_valid_pair.jsonl', encoding='utf-8', mode='r') as f:
    for line in f.readlines():
        try:
            line = line.strip()
            item = json.loads(line)
            src_item_id = item['src_item_id']
            tgt_item_id = item['tgt_item_id']
            src_item_emb = itemid2emb[src_item_id]
            tgt_item_emb = itemid2emb[tgt_item_id]
            threshold = 50
            out_item = {"src_item_id": src_item_id, "src_item_emb": src_item_emb, "tgt_item_id": tgt_item_id, "tgt_item_emb": tgt_item_emb, "threshold": threshold}
            f_out.write(json.dumps(out_item) + '\n')
        except Exception as e:
            print(e)
            print(line)
f_out.close()